version: "3.6"

services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    build: requirements/nginx
    depends_on:
      - wordpress
      - phpmyadmin
    ports:
      - "443:443"
    volumes:
      - /home/ubuntu/data/wp-data:/var/www/html
    networks:
      - my_network
  
  wordpress:
    image: wordpress
    container_name: wordpress
    restart: always
    build: requirements/wordpress
    env_file:
      - .env
      - terraform.env
    volumes:
      - /home/ubuntu/data/wp-data:/var/www/html
    networks:
      - my_network
  
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin 
    restart: always
    environment:
      - PMA_ARBITRARY=1
    networks:
      - my_network

networks:
  my_network:

volumes:
  wp-data:
    driver: local
    driver_opts:
      o: bind
      type: "nfs"
      device: "/home/ubuntu/data/wp-data"
