- name: Simple docker-compose start and stop because it seems mandatory
  hosts: aws_ec2
  tasks:
    - name: start containers
      command: sudo docker-compose -f app/srcs/docker-compose.yml start
      tags: ['start']

    - name: stop containers
      command: sudo docker-compose -f app/srcs/docker-compose.yml stop
      tags: ['stop']
